[PSocket]KILLSOC
[PSocket]Kills a connected socket, no matter the state of connection.
[PSocket]Use this to get rid of those annyoing [ Undecided ] people in
[PSocket]stats. To find the socket number to kill, use SOCINFO. Use
[PSocket]sparingly, and don't killsoc active players. That is why we have
[PSocket]Exo and Disconnect.
[PSocket]
[PSocket]See Also: SOCINFO
^
KILL <player/mobile>
Starts a fight with stated mobile (or player if playerkilling is allowed).
^
