version: '3.7'

services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile.PostgreSQL
    ports:
      - 5435:5432
    networks:
      - mud-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unmud
    volumes:
      - db_data:/var/lib/postgresql/data

  unmud:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/UnMUD
    volumes:
      - type: bind
        source: .
        target: /usr/src/UnMUD
    networks:
      - mud-network
    expose:
      - '5100'
    ports:
      - '5100:5100'
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - db

volumes:
  db_data:

networks:
  mud-network:
    driver: bridge