int gamecom(char *str,Boolean savecom);
char *getreinput(char *b);
int brkword(void);
int chkverb(void);
int chklist(char *word, char *lista[], int listb[]);
int Match(char *x, char *y);
void doaction(int n);
void quit_game(void);
void erreval(void);
Boolean parse_2(int vb);
int findprep(char *t);
