void deafcom (void);
void blindcom (void);
void curecom (void);
void dumbcom (void);
void cripplecom (void);
void colorcom(void);
void aloofcom(void);
void nobattlecom(void);
void saybackcom(void);
void autoexitcom(void);
void noslaincom (void);
void compactcom(void);
void nobeepcom(void);
void busycom(void);
void quietcom(void);
void briefcom (void);
void noinventorycom(void);
void awaycom(void);
void codecom (void);
void notalklinecom(int vb);
void talklinecom(int vb);
void noshoutcom ();
