# base image
FROM postgres:15.3-alpine

# Set Workdir
WORKDIR /Database

# Copy database files
COPY . /Database

# run create.sql on init
ADD DDL.sql /docker-entrypoint-initdb.d
ADD DML.sql /docker-entrypoint-initdb.d
ADD PROCEDURES.sql /docker-entrypoint-initdb.d
# ADD Procedures.sql /docker-entrypoint-initdb.d